version: "3.2"

services:
  sbtc-bridge-api:
    image: sbtc-bridge-api:latest   
    container_name: sbtc-bridge-api   
    build:
      context: ./docker
      args:
        BRIDGE_GIT_URI: https://github.com/stacks-network/sbtc-bridge-api.git
        BRIDGE_GIT_BRANCH: main
    ports:
      - 3010:3010
    environment:
      NODE_ENV: dev
      mongoDbUrl: mongodb
      mongoDbName: devnet
      mongoUser: devnet
      mongoPwd: devnet
      btcNode: bitcoin:18443
      btcRpcUser: devnet
      btcRpcPwd: devnet
      sbtcContractId: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.asset
      bitcoinExplorerUrl: http://mempool-web:8083
      stacksExplorerUrl: http://stacks-explorer:3020
      stacksApi: http://stacks-api:3999
      mempoolUrl: 'http://mempool-web:8083'
      blockCypherUrl: 'http://mempool-web:8083'
      host: http://localhost
      port: PORT
      network: devnet
      walletPath: 
      publicAppName: 'sBTC Bridge Devenv API'
      publicAppVersion: '1.0.0'

